### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dav-is** [comment]
Thanks!

**Comment by ghost** [comment]
Thank you for this extension :+1:

**Comment by ghost** [comment]
@dav-is could you submit a release so it'll be more convenient to install? thanks!

**Comment by dav-is** [comment]
@viralis Done! https://github.com/dav-is/flarum-ext-inviteonly/releases/tag/v0.1.0-beta3

**Pull request merged**
